apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeport-demo
  template:
    metadata:
      labels:
        app: nodeport-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80